### PR TITLE
Use full repository URL in package.json

### PR DESCRIPTION
**Pull request by zeke**
This will make a link to the repo show up in the sidebar of https://www.npmjs.com/package/auto-install

Cool package!

### CODE REVIEW

**Comment by macdonst** [comment]
@zeke I was just about to create the same PR. Makes it much easier to find from NPM. Maybe add `homepage` too?

```
"homepage": "https://github.com/siddharthkp/auto-install#readme",
"repository": {
   "type": "git",
   "url": "git://https://github.com/siddharthkp/auto-install.git"
},
```

**Comment by siddharthkp** [comment]
@zeke Cheers!
@macdonst Added 😄

**Comment by zeke** [comment]
Looks like this got reverted in https://github.com/siddharthkp/auto-install/commit/6bb02a80b8c7c26b38eb226194db9ff8585f5108

The shorthand version `siddharthkp/auto-install` you currently have specified will not be recognized by npm or the npm website. Using a fully-qualified URL string value for `repository` works fine.  The [normalize-package-data](https://github.com/npm/normalize-package-data) module takes care of turning it into an object:

> If repository field is a string, it will become an object with url set to the original string value, and type set to "git".

**Comment by siddharthkp** [comment]
@zeke,  npmjs website seems to understand the shorthand, I'm I missing something?

**Comment by zeke** [comment]
Wasn't there yesterday, but works now! ¯_(ツ)_/¯

**Pull request merged**
