### PR TITLE
Support for es6 modules

### PR DESCRIPTION
**Pull request by siddharthkp**
- Untested
- Needs backmerge

### CODE REVIEW

**Comment by siddharthkp** [comment]
Closes https://github.com/siddharthkp/auto-install/issues/11

**Comment by fregante** [comment]
It works with local files and npm modules, but `import memoize from 'lodash/memoize'` tries and fails to install `lodash/memoize` instead of `lodash`

Usually `/` means _access a file in a package_, but there are also [scoped packages](https://docs.npmjs.com/misc/scope):

``` js
import '@foo/bar/baz.js'
```

should run

``` sh
npm install @foo/bar
```

while this:

``` js
import 'foo/bar/baz.js'
```

should run

``` sh
npm install foo
```

**Comment by siddharthkp** [comment]
@bfred-it Trying to use `detective` and `detective-es6` both.

The problem now is:
`detective` fails when it sees an `import` statement.
and `detective-es6` only detects es6 modules.

I can solve this by asking the user to pick one flavor using a cli flag or config.

But, If a repository uses both styles, this fails.

Any suggestions?

**Comment by fregante** [comment]
My suggestion would be to open an issue for `detective/-es6`.

Alternatively you could revert to the previous commit and use a regex to get the right installable repo:

``` js
const regex = /^(@[^/]+\/)?([^/]+)/;
const simpleImport = 'foo';
const deepImport   = 'foo/bar/baz.js';
const scopedImport = '@foo/bar/baz.js';
console.log(simpleImport.match(regex)[0]); // -> 'foo'
console.log(deepImport  .match(regex)[0]); // -> 'foo'
console.log(scopedImport.match(regex)[0]); // -> '@foo/bar'
```

The regex works given that you've already filtered out local imports/requires. If not, here's a slight variation (`[^./]`): 

``` js
const regex = /^[^./](@[^/]+\/)?([^/]+)/;
const localImport  = './foo';
const simpleImport = 'foo';
const deepImport   = 'foo/bar/baz.js';
const scopedImport = '@foo/bar/baz.js';
console.log(localImport .match(regex));    // -> null
console.log(simpleImport.match(regex)[0]); // -> 'foo'
console.log(deepImport  .match(regex)[0]); // -> 'foo'
console.log(scopedImport.match(regex)[0]); // -> '@foo/bar'
```

**Pull request merged**
