### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by atilacamurca**
Extra https in url, causing a break link on npmjs.com

### CODE REVIEW

**Comment by siddharthkp** [comment]
@atilacamurca What am I missing here.

I see the link is `github.com/siddharthkp/auto-install` which links to `https://github.com/siddharthkp/auto-install`

**Comment by siddharthkp** [comment]
@atilacamurca Changed it to `siddharthkp/auto-install` in this [commit](https://github.com/siddharthkp/auto-install/commit/6bb02a80b8c7c26b38eb226194db9ff8585f5108#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7). Seems to be good now.

**Comment by atilacamurca** [comment]
sorry, I just access this package on npmjs.com and the link was `git://https://github.com/siddharthkp/auto-install/`, I thinks that was some kind of cache or something.

**Comment by atilacamurca** [comment]
I think I was on another branch `https://github.com/siddharthkp/auto-install/blob/revert-5-master/package.json#L9`

**Pull request closed without merging**
